### ISSUE TITLE
I can only start Moon with "sudo yarn start", i can't start with only "yarn start"

### ISSUE THREAD

**Issue by Vasalkar** [Spirtiks/moon#1]
When i try to start Moon without sudo this appears to me:

> 01:16:27 error: uncaughtException: listen EACCES 0.0.0.0:80
Error: listen EACCES 0.0.0.0:80
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1350:19)
    at listenInCluster (net.js:1408:12)
    at Server.listen (net.js:1492:7)
    at Function.listen (/home/user/moon/node_modules/express/lib/application.js:618:24)
    at resolve (/home/user/moon/src/web/index.js:40:53)
    at new Promise (<anonymous>)
    at module.exports.port (/home/user/moon/src/web/index.js:40:26)
    at Object.<anonymous> (/home/user/moon/src/index.js:31:14)

**Comment by Zaseth** [comment]
This is because it runs on port 80, which is pretty normal.
